pool_info:
  default_res: Chia reference pool
  name: The Reference Pool
  logo_url: https://www.chia.net/img/chia_logo.svg
  description: (example) The Reference Pool allows you to pool with low fees, paying out daily using Chia.
welcome_message: "Welcome to the reference pool!"
pool_fee: 0.01
pool_url: http://10.0.0.45
min_difficulty: 10
default_difficulty: 10
default_target_address: txch1h8vdax8vtspx7yt8kz6cwu2awymlgwmdr4qts8v643kusd2lmc5qht7ltq
authentication_token_timeout: 5
node_rpc_host: 127.0.0.1
node_rpc_port: 8555
partial_time_limit: 25
partial_confirmation_delay: 300
confirmation_security_threshold: 32
number_of_partials_target: 300
time_target: 86400
relative_lock_height: 32
logging:
  log_path: /var/log/chia
  log_filename: pool-server.log
  log_level: INFO
  log_maxfilesrotation: 7
  log_stdout: false
kafka_server: "127.0.0.1:9092"
share_topic: "share_chia"
farmer_topic: "farmer_chia"
server:
  server_host: 0.0.0.0
  server_port: 8082
  server_use_ssl: false
  server_ssl_crt: config/ssl/domain/domain_srv.crt
  server_ssl_key: config/ssl/domain/domain_srv.key
dev_mode: true
redis_server: "127.0.0.1"
redis_port: 6379
redis_passwd: "1234"
redis_db: 0
db_host: "127.0.0.1"
db_port: 3306
db_user: "root"
db_passwd: "1234"
db_name: "local"

