# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chia.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chia.proto',
  package='sharebase',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchia.proto\x12\tsharebase\"U\n\x08ShareMsg\x12\x12\n\nlauncherid\x18\x01 \x02(\t\x12\x0e\n\x06userid\x18\x02 \x01(\x05\x12\x12\n\ndifficulty\x18\x03 \x01(\x04\x12\x11\n\ttimestamp\x18\x04 \x01(\x12'
)




_SHAREMSG = _descriptor.Descriptor(
  name='ShareMsg',
  full_name='sharebase.ShareMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='launcherid', full_name='sharebase.ShareMsg.launcherid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userid', full_name='sharebase.ShareMsg.userid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='sharebase.ShareMsg.difficulty', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sharebase.ShareMsg.timestamp', index=3,
      number=4, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['ShareMsg'] = _SHAREMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShareMsg = _reflection.GeneratedProtocolMessageType('ShareMsg', (_message.Message,), {
  'DESCRIPTOR' : _SHAREMSG,
  '__module__' : 'chia_pb2'
  # @@protoc_insertion_point(class_scope:sharebase.ShareMsg)
  })
_sym_db.RegisterMessage(ShareMsg)


# @@protoc_insertion_point(module_scope)
